In [81]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import to_categorical
import mnist
import numpy as np

In [27]:
train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()

print(train_images.shape)
print(train_labels.shape)
print(test_images.shape)
print(test_labels.shape)
print(train_labels[:5])

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)
[5 0 4 1 9]


In [58]:
#normalize the images b/w -0.5 to 0.5for easier training
train_images = (train_images/255)-0.5
test_images = (test_images/255)-0.5

#reshape to flatten the images bcz the NN accepts a flattened list of values
train_images = train_images.reshape((-1,784))
test_images = test_images.reshape((-1,784))

print(train_images.shape)
print(test_images.shape)

(60000, 784)
(10000, 784)


In [59]:
#Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(784,)),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

In [62]:
model.compile(optimizer= 'adam', loss= 'categorical_crossentropy', metrics=['accuracy'])

In [63]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_25 (Dense)             (None, 64)                50240     
_________________________________________________________________
dense_26 (Dense)             (None, 64)                4160      
_________________________________________________________________
dense_27 (Dense)             (None, 10)                650       
Total params: 55,050
Trainable params: 55,050
Non-trainable params: 0
_________________________________________________________________


In [64]:
model.fit(train_images,to_categorical(train_labels), epochs=5, batch_size=32)

Epoch 1/5
60000/60000 [==============================] - 4s 63us/step - loss: 2.3028 - accuracy: 0.1110
Epoch 2/5
60000/60000 [==============================] - 3s 58us/step - loss: 2.3015 - accuracy: 0.1124
Epoch 3/5
60000/60000 [==============================] - 3s 58us/step - loss: 2.3014 - accuracy: 0.1124
Epoch 4/5
60000/60000 [==============================] - 4s 58us/step - loss: 2.3014 - accuracy: 0.1124
Epoch 5/5
60000/60000 [==============================] - 4s 70us/step - loss: 2.3014 - accuracy: 0.1124


In [50]:
model.evaluate(test_images,to_categorical(test_labels))

10000/10000 [==============================] - 0s 33us/step


[2.3010083526611327, 0.11349999904632568]

In [53]:
model.save_weights('model.h5')

In [54]:
#ReBuild the model later and load the saved weights
model = Sequential([
    Dense(64, activation='relu', input_shape=(784,)),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

model.save_weights('model.h5')

In [55]:
#predict first 5 images
predictions = model.predict(test_images[:5])

print(predictions)

[[0.12535644 0.09009404 0.05066996 0.15796055 0.12382241 0.10402704
  0.10829886 0.06803624 0.06883482 0.10289966]
 [0.1256248  0.09012627 0.0506279  0.15815236 0.12370288 0.10387842
  0.10818744 0.06802285 0.06890483 0.10277223]
 [0.12548693 0.09001873 0.05066469 0.15799399 0.12366465 0.10399213
  0.10830026 0.06797674 0.06887481 0.10302702]
 [0.1253067  0.0900939  0.05071063 0.15803966 0.12357721 0.1040739
  0.10833635 0.06804303 0.06890148 0.10291707]
 [0.12555078 0.0900896  0.05066116 0.1580826  0.12355679 0.10397066
  0.10818443 0.06804473 0.06897475 0.10288452]]


In [56]:
print(np.argmax(predictions, axis=1))

[3 3 3 3 3]


In [57]:
print(test_labels[:5])

[7 2 1 0 4]


# Hyperparameter tuning

In [65]:
from keras.optimizers import Adam

In [82]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(784,)),
    Dropout(0.5),
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(10, activation='softmax')
])


In [83]:
model.compile(optimizer= Adam(lr=0.005), loss= 'categorical_crossentropy', metrics=['accuracy'])

In [87]:
model.fit(train_images,to_categorical(train_labels), epochs=10, batch_size=64, validation_data=(test_images, to_categorical(test_labels)))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 3s 46us/step - loss: 2.3017 - accuracy: 0.1118 - val_loss: 2.3012 - val_accuracy: 0.1135
Epoch 2/10
60000/60000 [==============================] - 2s 41us/step - loss: 2.3017 - accuracy: 0.1115 - val_loss: 2.3015 - val_accuracy: 0.1135
Epoch 3/10
60000/60000 [==============================] - 3s 42us/step - loss: 2.3017 - accuracy: 0.1112 - val_loss: 2.3018 - val_accuracy: 0.1028
Epoch 4/10
60000/60000 [==============================] - 3s 42us/step - loss: 2.3017 - accuracy: 0.1118 - val_loss: 2.3015 - val_accuracy: 0.1135
Epoch 5/10
60000/60000 [==============================] - 3s 42us/step - loss: 2.3017 - accuracy: 0.1120 - val_loss: 2.3012 - val_accuracy: 0.1135
Epoch 6/10
60000/60000 [==============================] - 3s 44us/step - loss: 2.3016 - accuracy: 0.1120 - val_loss: 2.3016 - val_accuracy: 0.1028
Epoch 7/10
60000/60000 [==============================] - 3s 47us/st